name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          pip install -r requirements.txt
          python train.py
